### ISSUE TITLE
No License 

### ISSUE THREAD

**Issue by jarettrude** [idev1/rpihotspot#1]
Are you interested in adding an open source license to your script? 

I have been searching for months, going through numerous forums, and trying to follow various tutorials to get my RPi working as both a hotspot and a station. None of them worked.

Your script has been the only successful implementation I have found. I’m not sure why but I had to run it a few time to clear all the permission issues but it finally worked.

I would love to incorporate it into my photo booth project if you would permit it under an open source license.

**Comment by idev1** [comment]
Thanks Jarett for your evaluation on the script!

The reason behind not putting any "sudo" command in my script is that, i generally run the same script using "sudo" command in the terminal and hence, the script may not require all the individual commands used in this script to be prefixed with "sudo" command (for e.g., in run the same script with this command: "sudo ./setup-network.sh --install-upgrade" or "sudo ./setup-network.sh --install").

For your second question on providing the open source license, just want to tell you that, I am a bit new to Github and not sure about what type of open source licence I should use to help others make benefit of this script and I would require your guidance if you suggest me anything on the same topic.

I also struggled a lot to make my RPi to work as Access Point and Station network both and I made a deep search in internet about how this can be done. So, there are great and brilliant people present in the internet which shares their solutions which helps other to solve their problem and, I took the solution from from 1 of the person's recommendation present in Raspberry Pi Forum (and I just credited that forum reference by mentioning their site's reference in my script and therefore, you may find number of reference (for e.g., Raspberry Pi Forum, Stack Overflow etc.) given in this script). I am very thankful of those peoples contribution & recommendations through which, I took part of different different solutions and put it my final script to make it work and therefore, my intention is to help others also who are struggling with the same problem (by making this script publicly available).

Again, I would appreciate you if you guide/suggest me about open source licences or any other bugs i can solve if you found any.

Thanks
- Pankaj

**Comment by jarettrude** [comment]
Hey thank you for your response. Yeah, I am not sure why I ran into so many permission issues as I ran the script with sudo as you suggested. For me hostapd caused all my permission errors. Even with adding the sudo within the script, I had to run it it twice for it to forced hostapd to install and configure correctly. I am relatively new to coding and running scripts so it could very easily an issue with how I configured things. The forum you reference in your script was one of my starting points as well - I was unsuccessful in following it so I was very thankful to find your solution.

In terms of a license, it really depends on how you hope to have others share and use it. I am still learning a lot but came across a good resource github made to help you choose. 

https://choosealicense.com/

Both MIT and GNU GPL are popular to many projects I have come across.

To add a license you can go to insights within your project, then select community from the list on the left and then you should see License and the option to add one.

You can also move the reference to the forums that helped you build it from the script into your readme so that anyone coming across your project and link to them easier as well if they run into issues.

Cheers,

JR

**Comment by idev1** [comment]
Thanks Jerett for your helpful recommendations!!

I have also taken your suggestions from your recent pull request commits about documentation and part of those comments have been now added into Readme.md file. However, due to many feature enhancements into the script, I was unable to completely take your pull request so, I apologies for the same.

Although, the Access Point(AP) channel enhancement I did based on your observation but, I feel the change may not be necessary (but, good to have feature) as I believe that the Access Point(AP) channel will automatically get sync and moved to WiFi Station(wlan0) channel once the Station(STA) is up and running (no matter what channel your are specifying in hostapd configuration). 

Please try the below given changes/enhancements on a fresh and recent Raspbian OS and please let me know in case of any issues.

Based on your observations and issues, I have made below given changes in the script:
1. Supported "--ap-ssid" command parameter to input Access Point(AP) SSID setup.
2. Supported "--ap-password" command parameter to input Access Point(AP) Passphrase setup.
3. Supported "--ap-country-code" command parameter to input Access Point(AP) Country Code setup.
4. Supported "--ap-ip-address" command parameter to input Access Point(AP) static IP address setup.
5. Supported WLAN Station WiFi Channel to be injected into Access Point(AP) Channel configuration.
6. Supported feature to solve malfunctioning Hotspot Networking affected by improperly Powering-Off/Shutdown of Raspberry Pi.
7. Enhanced script to have usage documentation. Also made lot many corrections in the script based on future vision.
8. Added MIT License.
9. All the above changes are tested on Raspbian Stretch/Buster OS distro's.

**Comment by jarettrude** [comment]
These are all great enhancements. It works great on my current pi 3B+. I will play around more with it to see if I run into any bugs. I will see if I can get a few others to test as well.

I will open a new issue/ pull request if I come across anything.

Thank you for all your support on this! Your script has been a life saver.

**Comment by idev1** [comment]
Thanks Jerett for closing the issue.
