### ISSUE TITLE
Failed automatically fetch 2 packages on Buster

### ISSUE THREAD

**Issue by pppedrillo** [idev1/rpihotspot#11]
Hi

**Issue:** RPi 3b+. On latest Buster ( InRelease repo ) "--install-upgrade" fails automatically fetch 2 packages: "pciutils" and "gldriver-test".

**Flow:** By some reasons script is looking up for those packages in *.raspberry.org. Installation gets aborted with "can not fetch package" message in console.

**Workaround:** Before run the script, install these packages manually 
_sudo apt-get install pciutils_
_sudo apt-get install gldriver-test_
after that start the script as per instructions - it will finish successfully and everything will work just fine after restart.

Overall: @idev,1 thanks alot for this script, great job!

**Comment by idev1** [comment]
Hi, thanks for using the script and reporting an observed issue.
Just to inform you that I have not replicated this scenario in latest Buster OS but, it seems that the packages "pciutils" and "gldriver-test" has nothing to do with the execution of the script.
It might be a problem related to upgrading the existing OS using "--install-upgrade" option.
I will keep you updated once i fix this issue.

Thanks
Pankaj

**Comment by pppedrillo** [comment]
Hi,
and thanks for checking it! 
Indeed it looks very much as an issue with packages upgrade for OS itself.

**Comment by idev1** [comment]
Hi

I have fixed the bugs in a new branch "**rpihotspot-bugfixes**" script related to broken logic due to latest Raspbian Buster OS updates.

Can you please run this new branch script in your Buster Lite/Stretch OS and let me know if its solving your reported problem ? so that, it will help me in incorporating the same changes into "**master**" branch.

Below given are the fixes:

1. Replaced ```apt``` with ```apt-get``` as ```apt``` in recent Buster OS was enable to fix the broken links while OS upgrades. Hence, switched back to classic ```apt-get``` solution.

2. Handled ```doCleanup()``` function to properly operate over ```dhcpcd``` enabling releated to Buster OS upgrade problems.

3. Handled ```doInstall()``` function to properly check if the required dependencies are downloaded or not and if, its not downloaded then, prompting the error message and then, quickly exiting the installation process. 

Thanks
Pankaj

**Comment by pppedrillo** [comment]
Hi,

Tried and seems your changes did the trick. Script did its job without any error messages.
Thanks alot for fixing it!

**Comment by idev1** [comment]
Thanks for verifying the updates !
