### ISSUE TITLE
hostapd.service not loaded

### ISSUE THREAD

**Issue by remifleurance** [idev1/rpihotspot#13]
Tested on a fresh install of Raspbian Buster
hostapd.service generate errors, looks like it can't be stop / started

```
pi@raspberrypi:~/Documents/rpihotspot $ sudo ./setup-network.sh --install --ap-ssid="<ssid>" --ap-password="<pass>"

[WLAN]: wlan0 IP address: 192.168.178.20
[WLAN]: wlan0 IP Mask address: 255.255.255.0
[WLAN]: wlan0 IP Broadcast address: 192.168.178.255
[WLAN]: wlan0 Country Code: LU
[WLAN]: wlan0 Channel: 6
[Cleanup]: cleaning ...
[Remove]: /home/pi/network-setup/log/network.log
[Cleanup]: Cleaned all NAT IP Table entries.
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
[Cleanup]: DONE
Failed to stop hostapd.service: Unit hostapd.service not loaded.
```

Then ssh connection is lost and Raspberry Pi has to be restarted

Edit : tried with Raspbian Stretch, this issue did not occur.

**Comment by idev1** [comment]
Hi, thanks for using the script and reporting an issue.

The detailed instructions (in the form of comments is already provided for your previously reported issue. https://github.com/idev1/rpihotspot/issues/12#issuecomment-601083664).

Please refer the steps given in the said link and provide more updates/resolution if you found any so that, it will help me debug more into the issue.

Thanks
Pankaj

**Comment by idev1** [comment]
Hi

I have successfully replicated the problem you are facing while re-installing hotspot thru this script.
It seems that the latest/updated Raspbian Buster OS is either wrongly maintaining the nameserver entry in "/etc/resolv.conf" file or someother service is conflicting with the said file and hence, the said file don't seems to be maintaining the correct entry of nameserver.

Moreover, the script runs good in its first installation without any problem but, then fails on Buster OS while reinstalling.

The ``` doCleanup() ``` function cleans all the previously made network setup and then, restarts ``` dhcpcd ``` service to correctly function the internet services thru WiFi (using default wlan0 interface) so that, during next installation of hotspot network, the required dependencies (such as: hostapd, dnsmasq and iptables-persistent) can be downloaded from internet and it seems that, all these are properly function in Raspbian Stretch OS but, unfortunately, its seems that the latest updated Raspbian Buster OS is breaking this functionality which, you already confirmed. The said problem stops the internet and hence, the said dependencies wouldn't be downloaded from internet and then, it throws a weird error while installing and trying to stop **hostapd** service which is never installed using the below statement:

``` systemctl stop hostapd ``` (line no. 501 in script)

This thing you can also observe in your machine with latest Buster OS but, I will look into its possible resolution and would be updated you again.

Thanks
Pankaj

**Comment by idev1** [comment]
Hi

I have fixed the bugs in a new branch "**rpihotspot-bugfixes**" script related to broken logic due to latest Raspbian Buster OS updates.

Can you please run this new branch script in your Buster Lite/Stretch OS and let me know if its solving your reported problem ? so that, it will help me in incorporating the same changes into "**master**" branch.

Below given are the fixes:

1. Replaced ```apt``` with ```apt-get``` as ```apt``` in recent Buster OS was enable to fix the broken links while OS upgrades. Hence, switched back to classic ```apt-get``` solution.

2. Handled ```doCleanup()``` function to properly operate over ```dhcpcd``` enabling releated to Buster OS upgrade problems.

3. Handled ```doInstall()``` function to properly check if the required dependencies are downloaded or not and if, its not downloaded then, prompting the error message and then, quickly exiting the installation process. 

Thanks
Pankaj

**Comment by remifleurance** [comment]
Hi Pankaj,

I cloned the "rpihotspot-bugfixes" branch and gave it a try...
And it works !

It was interesting to have all the details behind this issue.
Thanks for your time, for having fixed this and for keeping your code up to date !
