### ISSUE TITLE
internet speed decreased

### ISSUE THREAD

**Issue by DholakiaDhruv** [idev1/rpihotspot#15]
heyy 
you wrote a great script but there is an issue i faced that my bandwidth gets decreased and speed gets slow is there any solution for that one more thing that i would suggest that try to connect in 6 th channel in script its 11th if i am not wrong so do let me know if i can change after installation

**Comment by ihorbond** [comment]
You can manually edit /etc/hostapd/hostapd.conf to select the channel etc. Channels 1, 6 and 11 are usually crowded. I did notice a significant speed drop too but I think it's just cause raspi wifi built it wifi is not that great

**Comment by idev1** [comment]
Thanks @DholakiaDhruv for using the script and reporting an issue !
Also, I am thankful of @ihorbond for providing the feedback to @DholakiaDhruv !

Just an additional note from my side is that, when we configure both: the Access Point (AP) and Station (STA) mode on the same WiFi chip of Raspberry Pi then, there is a known issue of dropping the WiFi signal strength in this managed mode and if the Internet WiFi signals are being shared by a connected device to Raspberry Pi AP and those connected devices also uses the streaming services (such as playing audio/video services over internet thru AP connection) then, there is a considerable amount of signal drop to the shared WiFi signals thru AP connection. But, apart from streaming services if, the connected devices to AP don't use the said streaming services and uses AP for sharing the local Intranet/Internet data (such as Realtime signal transfer thru Sensors or other devices, File sharing/transfer etc) then, in such scenarios, the signal strength don't matter that much and the shared services thru AP connection will still be faster.

There are people who already faced these kind of problems and concluded that, its a know issue of simultaneously using AP + STA mode. Please refer this link which talks about the same issue on Raspberry Pi forum (where I placed advertisement of this script):
https://lb.raspberrypi.org/forums/viewtopic.php?t=211542#p1570327

Another way of solving the same problem (which requires extra budget on our pocket) is to attach an additional (IEEE 802.11 compliant) WiFi dongle which, then connects to Internet (using external WiFi router) and then provides the Internet signals to the devices which are connected to AP thru IP Tables NAT entries. In this approach, the internal WiFi chip of Raspberry Pi will be acting as in AP mode only and therefore, the internal WiFi chip of Raspberry Pi will have less WiFi signal burden. Although, this approach will not put extra burden on internal WiFi chip of Raspberry Pi and may allow connected AP devices to smoothly use and access the said streaming services also but, this approach requires more maintenance (due to different types of WiFi dongle hardwares and their configurations) and hence, the scalability and portability will be compromised and therefore, i think, this approach may not be recommended. 

_But the people who still want to use this approach, an provision is given in the script to use the user input WLAN interface name to be used as STA mode interface. This user input WLAN interface option is **--wifi-interface** using which, a different external WLAN interface can be used (for e.g., --wifi-interface="wlan1" where, "wlan1" is the virtual interface where the external WiFi dongle will be connected and configured). Please read this issue link which motivated me to introduce "--wifi-interface" option: https://github.com/idev1/rpihotspot/issues/4_.

Lastly, there is short note i already provided for AP channel details for the existing query. Please read this link for more details on AP Channel: https://github.com/idev1/rpihotspot/issues/1#issuecomment-549126739.

This is the short description from the above link:

> Although, the Access Point(AP) channel enhancement I did based on your observation but, I feel the change may not be necessary (but, good to have feature) as I believe that the Access Point(AP) channel will automatically get sync and moved to WiFi Station(wlan0) channel once the Station(STA) is up and running (no matter what channel your are specifying in hostapd configuration).


I hope, the above information will be helpful for the asked queries.

Thanks
Pankaj
